export const ProjectsData = [
    {
        id: 1,
        title: "Showcase A",
        slug: "showcase-a",
        img: "/images/projects/proj_1.avif",
    },
    {
        id: 2,
        title: "Showcase B",
        slug: "showcase-b",
        vid: "/images/projects/proj_2.avif",
    },
    {
        id: 3,
        title: "Showcase C",
        slug: "showcase-c",
        img: "/images/projects/proj_3.avif",
    },
    {
        id: 4,
        title: "Showcase D",
        slug: "showcase-d",
        img: "/images/projects/proj_4.avif",
    },
    {
        id: 5,
        title: "Showcase E",
        slug: "showcase-e",
        vid: "/images/projects/proj_5.avif",
    },
    {
        id: 6,
        title: "Showcase F",
        slug: "showcase-f",
        img: "/images/projects/proj_6.avif",
    },
    {
        id: 8,
        title: "Showcase G",
        slug: "showcase-g",
        img: "/images/projects/proj_7.avif",
    },
    {
        id: 9,
        title: "showcase H",
        slug: "showcase-h",
        img: "/images/projects/proj_8.avif",
    },
    {
        id: 10,
        title: " showcase I",
        slug: "showcase-i",
        img: "/images/projects/proj_9.avif",
    },
    {
        id:11,
        title: "showcase J",
        slug: "showcase-j",
        img: "/images/projects/proj_10.avif",
    },
    {
        id: 12,
        title: "showcase K",
        slug: "showcase-k",
        img: "/images/projects/proj_11.avif",
    },
    {
        id: 13,
        title: "showcase L",
        slug: "showcase-l",
        img: "/images/projects/proj_12.avif",
    },
    {
        id: 14,
        title: "showcase M",
        slug: "showcase-m",
        img: "/images/projects/proj_13.avif",
    },
    {
        id: 15,
        title: "showcase N",
        slug: "showcase-n",
        img: "/images/projects/proj_14.avif",
    },
]